# Generated by Django 4.1 on 2022-08-24 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0002_hermanomayor_hermanomenor_madre_novia_padre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='HermanoMayor',
        ),
        migrations.DeleteModel(
            name='HermanoMenor',
        ),
        migrations.RemoveField(
            model_name='madre',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='novia',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='apellido',
        ),
    ]
