# Generated by Django 4.1 on 2022-09-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0004_entrenador_persona_ruta_delete_madre_delete_novia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='vigencia',
            field=models.IntegerField(),
        ),
    ]
