# Generated by Django 4.1 on 2022-09-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0005_alter_ruta_vigencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador',
            old_name='antiguedad',
            new_name='nivel',
        ),
        migrations.AddField(
            model_name='entrenador',
            name='ubicacion',
            field=models.CharField(default=20, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='ubicacion',
            field=models.CharField(default=20, max_length=50),
            preserve_default=False,
        ),
    ]
